name = "fastflash-api"
compatibility_date = "2024-01-01"

[env.production]
name = "fastflash-api"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[env.production.vars]
NODE_ENV = "production"

